news_sites:
  eluniversal:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.ce6-Tipo1_Titulo a'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: '.headline a'