news_sites:
 xataka:
    url: https://www.xataka.com.mx
    queries:
      homepage_article_links: '.base-asset-image a'
      article_body: '.article-content'
      article_title: '.article-header header h1 span'
eluniversal:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.ce6-Tipo1_Titulo a'
      article_body: '.field-name-body'
      article_title: '.Encabezado-Articulo h1'
elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: '.headline a'
      article_body: ''
      article_title: ''